version: 2
project_name: mcpwn

builds:
  - env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    main: ./cmd/mcpwn/main.go
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - mcpwn.yaml
      - README.md

nfpms:
  - package_name: mcpwn
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    maintainer: 'ParrotSec Team <team@parrotsec.org>'
    description: 'MCP server that allows LLMs to execute security tools on your local machine.'
    homepage: 'https://gitlab.com/parrotsec/project/mcpwn'
    license: GPL-3.0
    formats:
      - deb
    dependencies:
      - docker.io
    contents:
      - src: mcpwn.yaml
        dst: /etc/mcpwn/mcpwn.yaml
        type: config
      - src: README.md
        dst: /usr/share/doc/mcpwn/README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
